# Generated by Django 5.2 on 2025-04-18 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=45)),
                ('turno', models.CharField(max_length=45)),
                ('preceptor', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=1000)),
                ('apellido', models.CharField(max_length=1000)),
                ('dni_alumno', models.CharField(max_length=8)),
                ('edad', models.CharField(max_length=2)),
                ('gmail', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
                ('id_curso_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
            ],
        ),
    ]
